### ISSUE TITLE
Small timeout for connect to robot

### ISSUE THREAD

**Issue by NelaMm** [robofit/arcor2_editor#109]
After create scene contain robot service (created with timeout problem, but service is anyway added) there is timeout problem create project with this scene (after this fail is open scene with this service)

[2020-07-5--14-28-47.zip](https://github.com/robofit/arcor2_editor/files/4592932/2020-07-5--14-28-47.zip)

**Comment by Kapim** [comment]
Fixed in #110  by raising default timeout to 10s and service related stuff to 30s. Should be (hopefully) enough. Released in bugfix version 0.5.2.
