### ISSUE TITLE
Stop button

### ISSUE THREAD

**Issue by ZdenekM** [robofit/arcor2_editor#114]
- AREditor should enable user to stop robot movement. However, user should be somehow warned that it is not fail-safe solution.
- Probably it could be a big red button somewhere in the corner (easily reachable), displayed only when robot moves?

**Comment by ZdenekM** [comment]
@Kapim Maybe this can be generalized - it does not apply only to robots (e.g. user might want to cancel movement of arbitrary machine or even printing of a label). We can add to the action metadata information whether the action can be cancelled and there will be RPC to cancel executed action. Server will get name of the method to call in order to cancel action in a similar way to dynamic parameters (there will be dict with mapping of actions to method responsible to cancelling actions). What do you think?

**Comment by Kapim** [comment]
Implemented
