### ISSUE TITLE
Object name visualization

### ISSUE THREAD

**Issue by ZdenekM** [robofit/arcor2_editor#138]
Object name label should be independent on object's dimensions and rotation. It should (probably) behave like a billboard - be always oriented towards user?

![Screenshot from 2020-06-17 14-49-44](https://user-images.githubusercontent.com/1199396/84900027-cd62fe80-b0a9-11ea-9dd0-2e00527c47cf.png)

**Comment by xBambusekD** [comment]
Updated in #161:
![image](https://user-images.githubusercontent.com/26470087/86955479-ef571a80-c157-11ea-9d0e-901e1c958d77.png)

But issues with text overlapping occured (_tester_ name not hidden by box object):
![image](https://user-images.githubusercontent.com/26470087/86955623-2b8a7b00-c158-11ea-92b3-7666dfdcc8a2.png)

**Comment by ZdenekM** [comment]
@xBambusekD It looks good!
