### ISSUE TITLE
Floating button instead of tile to create scene or project

### ISSUE THREAD

**Issue by ZdenekM** [robofit/arcor2_editor#145]
"+" tile could be little bit hard to reach if there are many scenes or projects.

![Screenshot from 2020-07-02 16-46-35](https://user-images.githubusercontent.com/1199396/86373445-b1ec1c00-bc83-11ea-8359-e974840e513e.png)

Maybe "+" icon in the bottom right corner (similar to "pen" icon to start new e-mail in GMail app) would do better job?

![unnamed](https://user-images.githubusercontent.com/1199396/86373692-f677b780-bc83-11ea-8846-24a20a5594a6.png)

**Comment by Kapim** [comment]
![image](https://user-images.githubusercontent.com/2621793/89630841-3263f500-d8a0-11ea-8d58-98a80e8fc6ca.png)
