### ISSUE TITLE
Default camera position parallel to the "ground" plane

### ISSUE THREAD

**Issue by ZdenekM** [robofit/arcor2_editor#146]
When I open a new scene, the camera is parallel to the "ground" plane which is not really convenient.

![Screenshot from 2020-07-02 16-52-10](https://user-images.githubusercontent.com/1199396/86374184-8cabdd80-bc84-11ea-9bc5-bd94c8c02a6a.png)

**Comment by xBambusekD** [comment]
Fixed in #161
