### ISSUE TITLE
Some controls are out of screen in portrait mode

### ISSUE THREAD

**Issue by ZdenekM** [robofit/arcor2_editor#148]
AREditor version 0.7.2

![Screenshot_20200706-081425_AREditor](https://user-images.githubusercontent.com/1199396/86562953-da199a80-bf63-11ea-8a6a-00c86f622ac2.jpg)
![Screenshot_20200706-081357_AREditor](https://user-images.githubusercontent.com/1199396/86562957-dab23100-bf63-11ea-8e23-08869dd194c6.jpg)

**Comment by Kapim** [comment]
fixed
