### ISSUE TITLE
Objects not shown correctly when package runs

### ISSUE THREAD

**Issue by ZdenekM** [robofit/arcor2_editor#154]
After "Build and run", the box becomes huge.

![Screenshot_20200706-082819_AREditor (1)](https://user-images.githubusercontent.com/1199396/86568490-3cc36400-bf6d-11ea-9d74-1b6dce08b399.jpg)
![Screenshot_20200706-083149_AREditor](https://user-images.githubusercontent.com/1199396/86568491-3d5bfa80-bf6d-11ea-967e-53e688b319a8.jpg)

**Comment by Kapim** [comment]
Bug in ARServer, fixed -> closing
