### ISSUE TITLE
Translation gizmo not aligned with the object

### ISSUE THREAD

**Issue by ZdenekM** [robofit/arcor2_editor#159]
![Screenshot_20200706-102546_AREditor](https://user-images.githubusercontent.com/1199396/86575653-ea3b7500-bf77-11ea-8ca1-ae8ec1e192c8.jpg)

**Comment by xBambusekD** [comment]
This is not a bug, it's done on purpose. Translation gizmo is set to translate in coords relative to the world origin ( =calibrated marker). In case there will be need of translating the object in local coords, we need to add two different translation toggles.

**Comment by ZdenekM** [comment]
Ok, thanks for clarification.
