### ISSUE TITLE
Some texts in status line / menus are hidden by virtual objects

### ISSUE THREAD

**Issue by ZdenekM** [robofit/arcor2_editor#162]
AREditor version: 0.7.2

See video: https://photos.app.goo.gl/xF5d2HEoR1SBbCHw7

**Comment by Kapim** [comment]
@xBambusekD you fixed this? I can't reproduce this in your latest devel build..

**Comment by xBambusekD** [comment]
I wasn't working on this bug at all. It was probably fixed unpurposely by changing the shader of LiberationSans SDF Material to TextMeshPro/Mobile/Distance Field Overlay (for object names display). Shader switch on this font changed it on all texts using this font, and as I am looking, this font is used almost everywhere. So I assume, it is fixed.
![image](https://user-images.githubusercontent.com/26470087/87327663-9eb73700-c534-11ea-94b5-f5a665dd4421.png)

**Comment by Kapim** [comment]
Nice :)
