### ISSUE TITLE
Failed request not handled / notified

### ISSUE THREAD

**Issue by ZdenekM** [robofit/arcor2_editor#24]
For instance when AR Server fails to open scene (as there is some unknown object type) it returns false and error message. This should be communicated to the user. 
![Screenshot from 2020-03-24 11-38-49](https://user-images.githubusercontent.com/1199396/77416535-3d702a00-6dc4-11ea-9d5d-43f9f43adcd4.png)

**Comment by Kapim** [comment]
Should be fixed in next release

**Comment by Kapim** [comment]
Fixed in #28

**Comment by Kapim** [comment]
It still happens in some cases, I need to investigate further.

**Comment by Kapim** [comment]
Seems to be fixed.
