### ISSUE TITLE
User experience

### ISSUE THREAD

**Issue by NelaMm** [robofit/arcor2_editor#33]
- enable copy of action in action point

- hide or collapse list of actions on AP (collapse on doubleclick), connect action in list -> input(first) and output(last) action connect to else AP(first/last action) - for solving problem with overlaping action of others action points

- right click on AP inside collision object (safty collision box)

- text next checkbox "update position" is not visible

- typo Visibiilty - section Project -> right click on object next to button Create action point

**Comment by Kapim** [comment]
Separated to issues #34, #35, #36, #37 and #38 to better track changes in each issue
