### ISSUE TITLE
Right click on AP inside collision object (safty collision box)

### ISSUE THREAD

**Issue by Kapim** [robofit/arcor2_editor#36]

**Comment by Kapim** [comment]
@NelaMm What do you mean by this issue? Is it bug or enhancement request?

**Comment by NelaMm** [comment]
It is enhancement request. For example: We add collision box and we have action point inside collision box (grab something from box), AP is visibile when box visiblility is on 50% but on right-click I edit box not AP inside. It will be good when we can edit it (for example on some else type of click or another way)

**Comment by Kapim** [comment]
Ok, now i see. At the moment, you can globally turn off all interaction with action objects using Action objects settings menu (the gear button on bottom panel)
![image](https://user-images.githubusercontent.com/2621793/78002699-e2948080-7337-11ea-9d31-34d370ea8fa7.png)

In this menu you can set if action objects should be visible and interactive. Below this settings you can find list of all action objects in scene/project, which can be used to open menu of all objects, regardles of their visibility or interactivity.
![image](https://user-images.githubusercontent.com/2621793/78002854-17a0d300-7338-11ea-8043-5b410681f9ad.png)

Do you think that it would be usefull to enable/disable interactivity of each object individually in action object menu or is this global approach sufficent?

Another way how to interact with AP inside object is using menu of action object, which contain list of its action points: 
![image](https://user-images.githubusercontent.com/2621793/78003294-b9c0bb00-7338-11ea-8f3c-735a09fe7c76.png)

**Comment by NelaMm** [comment]
Sorry I didn't noticed this option.  I think a global approach is sufficient for now.

**Comment by Kapim** [comment]
Ok, no problem, these features will be covered in user manual in the future.
