### ISSUE TITLE
Enable show actual position of the end-effector

### ISSUE THREAD

**Issue by NelaMm** [robofit/arcor2_editor#47]

**Comment by Kapim** [comment]
Do you mean all the time show position of EE, or saved position/orientation withing action point, or something else?

**Comment by NelaMm** [comment]
I mean all the time show the position of EE. It helps to orient in the scene. For example, sometimes I rotate the scene and then forget the starting position. The EE position helps me orient in the scene and connection between the real scene with the robot and the scene in the AR editor. It is difficult to imagine the relationship between the scene and the robot when the robot isn't show.
Maybe for each EE can be some checkbox, indicate that the EE position have to be show in scene.

**Comment by Kapim** [comment]
Ok, for the "computer" version of editor this sounds reasonable, we will probably implement this once the URDF will be available through REST

**Comment by Kapim** [comment]
Comment from duplicated issue #56

![image](https://user-images.githubusercontent.com/2621793/79331996-562fb380-7f1c-11ea-9a6d-c249b3b81e03.png)

**Comment by Kapim** [comment]
Implemented in 0.5.0
