### ISSUE TITLE
Visualisation of connection between action object and action point

### ISSUE THREAD

**Issue by Kapim** [robofit/arcor2_editor#49]
Maybe using thin straigth line? @xBambusekD can you look at this?

**Comment by xBambusekD** [comment]
Implemented using straight transparent line, when action object is selected, connections will highlight as well.

![Screenshot (56)](https://user-images.githubusercontent.com/26470087/79466405-d6c5e100-7ffc-11ea-8bf8-bad530e74e0f.png)
