### ISSUE TITLE
Change of AP name doesn't work

### ISSUE THREAD

**Issue by rstourac** [robofit/arcor2_editor#54]
Steps to reproduce:

1. Right click on AP in AR editor
2. Focus text box with name and update the text
3. Leave the text box by clicking on another AP

Observation:
AP name is not updated when you get back. Old value is still there.

**Comment by Kapim** [comment]
Yes, renaming of anything does not work well with current version. It is however fixed in currently developed version (#48), which is under testing at the moment and will be released this week.
