### ISSUE TITLE
Make possible to visualize end-effector current position

### ISSUE THREAD

**Issue by rstourac** [robofit/arcor2_editor#56]
**Abstract**
It is difficult to orient in difficult scenes with many collision objects and APs. We need to introduce tools to improve this.

**Extension**
Operator wants to be able to see current position of end-effector in AR editor, which allows him to get better idea where is located each collision object and AP in the scene.
Feature should be possible switch on/off.

**Comment by Kapim** [comment]
Already requested in #47
