### ISSUE TITLE
Wrong carrying point when placing collision object to the scene

### ISSUE THREAD

**Issue by rstourac** [robofit/arcor2_editor#58]
**Observation:**
When placing collision object to the scene it is always carried by the center of a object (center of the object is attached to end-effector), which makes impossible correctly place already existing objects (I cannot move end-effector to be inside them). 

Collision objects should be carried by the point laying on the top of it (center of top plane).

**Comment by ZdenekM** [comment]
I think that this feature was originally meant for placing virtual collision objects into the scene so it is not really a bug. For real objects, there is mesh-based aiming. But we can definitely improve this as it might be useful for real objects which have no exact model available or do not need to be aimed precisely. Closing this, as there is https://github.com/robofit/arcor2/issues/75 proposing enhancement solving the problem you observed.
