### ISSUE TITLE
Newly created AP cannot be clicked until AR editor restart

### ISSUE THREAD

**Issue by rstourac** [robofit/arcor2_editor#62]
**Steps to reproduce:**

1. Create new Project from Scene with one collision object in it. 
2. Add new AP and aim its position and orientation by robot
3. Add another AP.

**Observation:**
The latest AP object cannot be activated neither be direct right-click nor through collision object. To be able to interact with this AP operator needs to save the Project and restart AR editor.

**Comment by Kapim** [comment]
Fixed
