### ISSUE TITLE
NullReferenceException when clicking on plane icon

### ISSUE THREAD

**Issue by ZdenekM** [robofit/arcor2_editor#68]
![Screenshot from 2020-04-16 13-32-56](https://user-images.githubusercontent.com/1199396/79451453-e1757b80-7fe6-11ea-822e-206ce7c9183c.png)

If the button does not make sense on PC, it should be hidden or disabled.

**Comment by xBambusekD** [comment]
Fixed: button is automatically hidden for PC version
