### ISSUE TITLE
"+" icon visibility

### ISSUE THREAD

**Issue by ZdenekM** [robofit/arcor2_editor#70]
The "+" icon to create global AP should not be available during scene editing or should be disabled.

![Screenshot from 2020-04-16 13-39-14](https://user-images.githubusercontent.com/1199396/79452008-be979700-7fe7-11ea-812c-d659101e9521.png)

**Comment by Kapim** [comment]
Fixed in #73

**Comment by ZdenekM** [comment]
I just updated from master branch and "+" seems to be still there.

**Comment by Kapim** [comment]
Accidentaly removed by #75 (wrong merge), should be fixed now by #81
