### ISSUE TITLE
Tracking-related notifications on PC

### ISSUE THREAD

**Issue by ZdenekM** [robofit/arcor2_editor#71]
...should not be displayed

**Comment by xBambusekD** [comment]
Which notifications are being displayed? AR stuff should be completely turned off when using PC version.

**Comment by ZdenekM** [comment]
![Screenshot from 2020-04-16 13-42-16](https://user-images.githubusercontent.com/1199396/79454926-5dbe8d80-7fec-11ea-808e-1e600327a273.png)

Sorry - forget to attach screenshot.

**Comment by Kapim** [comment]
Closing this as it is caused by tracking managed instance in standalone version, which is being addressed in #76
