### ISSUE TITLE
Different API versions notification

### ISSUE THREAD

**Issue by ZdenekM** [robofit/arcor2_editor#90]
* Contains typo.
* Should (probably) be shown only when:
  * minor version differs (when major == 0)
  * major version differs (when major > 0)

![Screenshot from 2020-04-21 08-32-48](https://user-images.githubusercontent.com/1199396/79832995-db96e600-83aa-11ea-9ba6-98c380bb6012.png)

**Comment by Kapim** [comment]
Well, I think it is good to inform the user that he has outdated server or editor. Maybe change the message to something like - "Editor update recommended to match server API version" when patch version of editor is lover than server and vice versa?

**Comment by Kapim** [comment]
fixed
