### ISSUE TITLE
Create AP above the object

### ISSUE THREAD

**Issue by ZdenekM** [robofit/arcor2_editor#99]
Do not take orientation of the object into account when creating action point.
![Screenshot from 2020-04-22 07-04-39](https://user-images.githubusercontent.com/1199396/79942705-bb792c80-8467-11ea-848b-6f16ef1adf1a.png)

**Comment by ZdenekM** [comment]
![Screenshot from 2020-04-24 10-27-30](https://user-images.githubusercontent.com/1199396/80191616-3a13cc80-8616-11ea-949a-a004c5f28cbc.png)

Position-setting gizmo should not be rotated as well.

**Comment by Kapim** [comment]
Fixed
